#!/usr/bin/env bash
# script installs nginx in a server
# script configures nginx to listen on port 80 
# and also to return a page with hello world 
# when a request in sent to nginx root

# update the server and install nginx
sudo apt update -y
sudo apt get-install nginx -y

# Creating new index
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Starting nginx
sudo service nginx start
