#!/usr/bin/env bash
# This script pings ip based as cmd-line argument 5 times
if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
else
    # call the ping command 5 times on the argument passed after the name of the file
    ping -c 5 "$1"
fi
