#!/usr/bin/env bash
# This script print bad luck numbers from different countries

count=1
while [ $count -le 20 ]
do
	echo "$count"
	case $count in
		4)
			echo -e "bad luck from China"
			;;
		9)
			echo -e "bad luck from Japan"
			;;
		17)
			echo -e "bad luck from Italy"
			;;
	esac
	((count++))
done
