#!/usr/bin/env bash
# This script changes local host and redirects facebook
# create a copy of localhost file to the home directory
cp /etc/hosts ~/hosts.new
# use sed to find a replace
sed -i 's/127.0.0.1/127.0.0.2/ ~/host.new'
sed -i '/2i8.8.8.8 facebook.com/ ~/host.new'
# overwrite the localhost file with the new changes made
cp -f ~/hosts.new /etc/hosts
