#!/usr/bin/env bash
# Adds IP address to /etc/hosts
# create a copy of localhost file to the home directory
cp /etc/hosts ~/hosts.new
# use sed to find a replace and insert
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
# overwrite the localhost file with the new changes made
cp -f ~/hosts.new /etc/hosts
